### ISSUE TITLE
Use locales to get the `ampm` default value

### ISSUE THREAD

**Issue by ocarreterom** [excid3/combined_time_select#19]
Could be an improvement to get the default value for `ampm` from locales.

```yml
es:
  combined_time_select:
    am_pm: false
```
